title: AI Curation Directory
description: Auto-updating directory of AI resources（毎日自動更新）
url: "https://karasu12071128-creator.github.io"   # 末尾スラッシュなし
baseurl: "/ai-curation-directory"                  # ここが超重要

markdown: kramdown
theme:
plugins: []
exclude:
  - .github
  - scripts
  - data