name: daily-refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 毎日 00:00 UTC

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Fetch HF
        run: python scripts/fetch_hf.py > hf.json

      - name: Fetch GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/fetch_github.py > gh.json

      - name: Merge & Rank
        run: python scripts/merge_rank.py hf.json gh.json > data/resources.json

      - name: Make daily diff
        run: python scripts/make_diff.py data/resources.json > data/diff.json

      - name: Export CSV for sale
        run: python scripts/export_csv.py data/resources.json > data/resources.csv

      - name: Publish artifacts to docs
        run: |
          cp data/resources.json docs/resources.json
          cp data/resources.csv docs/resources.csv

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update data" || echo "No changes to commit"
          git push