name: daily-refresh
on:
  schedule:
    - cron: '15 2 * * *'  # UTC 02:15 ≒ JST 11:15
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Fetch HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/fetch_hf.py > hf.json

      - name: Fetch GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/fetch_github.py > gh.json

      - name: Merge & Rank
        run: python scripts/merge_rank.py hf.json gh.json > data/resources.json

      - name: Make daily diff
        run: |
          d=$(date -u +'%Y-%m-%d')
          mkdir -p data/updates
          cp data/resources.json "data/updates/${d}.json"

      - name: Export CSV for sale
        run: python scripts/export_csv.py data/resources.json data/resources.csv

      - name: Commit & push
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "auto: daily refresh"
            git push
          fi
